CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "stylesheets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "name" varcher(64),
  "css_content" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "targets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "stylesheet_id" integer,
  "url_pattern" varchar
);

COMMENT ON COLUMN "stylesheets"."css_content" IS 'Le code CSS brut';

COMMENT ON TABLE "targets" IS 'Sépare les URLs du contenu pour permettre à un style de s’appliquer à plusieurs sites';

COMMENT ON COLUMN "targets"."url_pattern" IS 'L’URL ou le regex où le CSS s’applique';

ALTER TABLE "stylesheets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "targets" ADD FOREIGN KEY ("stylesheet_id") REFERENCES "stylesheets" ("id") DEFERRABLE INITIALLY IMMEDIATE;
